/**
 * @fileoverview gRPC-Web generated client stub for ping
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.1
// source: src/ping/ping.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as src_ping_ping_pb from '../../src/ping/ping_pb'; // proto import: "src/ping/ping.proto"


export class PingTestClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorPing = new grpcWeb.MethodDescriptor(
    '/ping.PingTest/Ping',
    grpcWeb.MethodType.UNARY,
    src_ping_ping_pb.PingRequest,
    src_ping_ping_pb.PingResponse,
    (request: src_ping_ping_pb.PingRequest) => {
      return request.serializeBinary();
    },
    src_ping_ping_pb.PingResponse.deserializeBinary
  );

  ping(
    request: src_ping_ping_pb.PingRequest,
    metadata?: grpcWeb.Metadata | null): Promise<src_ping_ping_pb.PingResponse>;

  ping(
    request: src_ping_ping_pb.PingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: src_ping_ping_pb.PingResponse) => void): grpcWeb.ClientReadableStream<src_ping_ping_pb.PingResponse>;

  ping(
    request: src_ping_ping_pb.PingRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: src_ping_ping_pb.PingResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ping.PingTest/Ping',
        request,
        metadata || {},
        this.methodDescriptorPing,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ping.PingTest/Ping',
    request,
    metadata || {},
    this.methodDescriptorPing);
  }

}

